repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://codeberg.org/hxr404/nix-pre-commit-hooks
    rev: v1.1.0
    hooks:
      - id: nix-check-flake
